### ISSUE TITLE
The provided pre-trained model cannot be downloaded

### ISSUE THREAD

**Issue by ghost** [JiawangDan/DFAM#1]
Thank you for the usefull repo.

I want to compare my method with your method. But the provided pre-trained model cannot be downloaded:
https://pan.baidu.com/s/1gwBtig-SIOzrpEyMczLfkw

Please release it on google drive if possible.

Thank you so much

**Comment by JiawangDan** [comment]
https://drive.google.com/file/d/1DGh5oVfw1p5yjanNdjZQOngx-JYzarhj/view?usp=sharing

**Comment by JiawangDan** [comment]
@Iman1221 https://drive.google.com/file/d/1DGh5oVfw1p5yjanNdjZQOngx-JYzarhj/view?usp=sharing
